import numpy as np
import pandas as pd


###   First initialization   ###
Matrix = {'column0' : [1, 2, 3], 'column1' : [1, 3, 5], 'column2' : [1, 4, 7], 'column3' : [1, 5, 9]}
firstDataFrame = pd.DataFrame(Matrix)
print("1st Dataframe is generated by using \'Dictionary\' data structure.")
print()
print(firstDataFrame)
print()
print()


###   Second initialization   ###
Array = np.array([[2, 4, 6], [3, 6, 9], [4, 8, 12], [5, 10, 15]])
secondDataFrame = pd.DataFrame(Array, columns = ['column0', 'column1', 'column2'])
print("2nd Dataframe is generated by using \'Numpy Array\' data structure.")
print()
print(secondDataFrame)
